package org.eeasonloo.constant;

/**
 * 消息常量
 */
public class MessageConstant {
    public static final String DELETE_CHECKITEM_FAIL = "Failed to delete check item";
    public static final String DELETE_CHECKITEM_SUCCESS = "Deleting check items succeeded";
    public static final String ADD_CHECKITEM_SUCCESS = "Add check item success";
    public static final String ADD_CHECKITEM_FAIL = "Add check item failed";
    public static final String EDIT_CHECKITEM_FAIL = "Failed to edit check item";
    public static final String EDIT_CHECKITEM_SUCCESS = "Edit Check Item Success";
    public static final String QUERY_CHECKITEM_SUCCESS = "Query Check Item Success";
    public static final String QUERY_CHECKITEM_FAIL = "Query check item failed";
    public static final String UPLOAD_SUCCESS = "Upload successful";
    public static final String ADD_CHECKGROUP_FAIL = "Failed to add checklist";
    public static final String ADD_CHECKGROUP_SUCCESS = "Adding a new inspection team was successful";
    public static final String DELETE_CHECKGROUP_FAIL = "Failure to delete inspection group";
    public static final String DELETE_CHECKGROUP_SUCCESS = "Deleting a check group was successful";
    public static final String QUERY_CHECKGROUP_SUCCESS = "Querying the check group was successful";
    public static final String QUERY_CHECKGROUP_FAIL = "Querying the check group failed";
    public static final String EDIT_CHECKGROUP_FAIL = "Failed to edit the check group";
    public static final String EDIT_CHECKGROUP_SUCCESS = "Edit check group success";
    public static final String PIC_UPLOAD_SUCCESS = "Image upload successful";
    public static final String PIC_UPLOAD_FAIL = "Image upload failed";
    public static final String ADD_SETMEAL_FAIL = "Failed to add setmeal";
    public static final String ADD_SETMEAL_SUCCESS = "Add setmeal success";
    public static final String IMPORT_ORDERSETTING_FAIL = "Bulk import of appointment setting data failed";
    public static final String IMPORT_ORDERSETTING_SUCCESS = "Bulk import of appointment setting data was successful";
    public static final String GET_ORDERSETTING_SUCCESS = "Getting appointment setting data was successful";
    public static final String GET_ORDERSETTING_FAIL = "Failed to get appointment setting data";
    public static final String ORDERSETTING_SUCCESS = "Appointment setting success";
    public static final String ORDERSETTING_FAIL = "Appointment setting failed";
    public static final String QUERY_MEMBER_SUCCESS = "Member information query successful";
    public static final String QUERY_MEMBER_FAIL = "Failed to query member information";
    public static final String ADD_MEMBER_FAIL = "Failed to add member";
    public static final String ADD_MEMBER_SUCCESS = "Add member success";
    public static final String DELETE_MEMBER_FAIL = "Failed to delete member";
    public static final String DELETE_MEMBER_SUCCESS = "Deleting members was successful";
    public static final String EDIT_MEMBER_FAIL = "Failed to edit member";
    public static final String EDIT_MEMBER_SUCCESS = "Edit Member Success";
    public static final String TELEPHONE_VALIDATECODE_NOTNULL = "Neither the phone number nor the verification code can be empty";
    public static final String LOGIN_SUCCESS = "Login successful";
    public static final String VALIDATECODE_ERROR = "Error entering verification code";
    public static final String QUERY_ORDER_SUCCESS = "Reservation information query successful";
    public static final String QUERY_ORDER_FAIL = "Failed to query reservation information";
    public static final String DELETE_ORDER_SUCCESS = "Delete order Successfully";
    public static final String DELETE_ORDER_FAIL = "Failed to delete order";
    public static final String QUERY_SETMEALLIST_SUCCESS = "Success in querying package list data";
    public static final String QUERY_SETMEALLIST_FAIL = "Query for package list data failed";
    public static final String QUERY_SETMEAL_SUCCESS = "Success in querying setmeal data";
    public static final String QUERY_SETMEAL_FAIL = "Querying setmeal data failed";
    public static final String SEND_VALIDATECODE_FAIL = "Failed to send verification code";
    public static final String SEND_VALIDATECODE_SUCCESS = "Verification code sent successfully";
    public static final String SELECTED_DATE_CANNOT_ORDER = "The selected date is not available for medical examination appointments";
    public static final String ORDER_FULL = "Appointment is full";
    public static final String HAS_ORDERED = "The appointment has been completed and cannot be repeated";
    public static final String ORDER_SUCCESS = "Appointment successful";
    public static final String GET_USERNAME_SUCCESS = "Success in getting the name of the currently logged in user";
    public static final String GET_USERNAME_FAIL = "Failed to get the name of the currently logged in user";
    public static final String GET_MENU_SUCCESS = "Get current login user menu success";
    public static final String GET_MENU_FAIL = "Failed to get the menu of the currently logged in user";
    public static final String GET_MEMBER_NUMBER_REPORT_SUCCESS = "Success in getting member statistics";
    public static final String GET_MEMBER_NUMBER_REPORT_FAIL = "Failed to get member statistics";
    public static final String GET_SETMEAL_COUNT_REPORT_SUCCESS = "Success in getting statistics on packages";
    public static final String GET_SETMEAL_COUNT_REPORT_FAIL = "Failed to get package statistics";
    public static final String GET_BUSINESS_REPORT_SUCCESS = "Success in obtaining operational statistics";
    public static final String GET_BUSINESS_REPORT_FAIL = "Failed to get operational statistics";
    public static final String GET_SETMEAL_LIST_SUCCESS = "Success in querying package list data";
    public static final String GET_SETMEAL_LIST_FAIL = "Failed to query package list data";
}
